receitas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.Contato.as_view(), name="contact"),
    path('receitas/<int:pk>', views.DetalheDaReceita.as_view(), name="detail"),
    path('', views.ListaDeReceitas.as_view(), name="list"),
    path('create/', views.criar_receita, name='create'),
    path('about/', views.Sobre.as_view(), name="about"),
    path('update/<int:pk>/', views.AtualizarReceita.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeletarReceita.as_view(), name='delete'),
    path('search/', views.buscar_receitas, name="search"),
    path('comment/<int:post_id>', views.criar_comentario, name="comment"),
    path('categorias/', views.ListaDeCategorias.as_view(), name="categorias"),
    path('lista/<int:pk>/', views.listar_receitas, name="receitas"),
]

suriabreads/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('receitas.urls')),
    path('admin/', admin.site.urls),
]

receitas/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Category(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=500)

    def __str__(self):
        return f'{self.nome}'

class Post(models.Model):
    nome = models.CharField(max_length=100)
    tempo_de_preparo = models.IntegerField()
    foto_url = models.URLField(max_length=1000, null=True)
    ingredientes = models.CharField(max_length=1000)
    data = models.DateTimeField(auto_now_add=True)
    categorias = models.ManyToManyField(Category)

    def __str__(self):
        return f'{self.nome} ({self.tempo_de_preparo})'

class Comment(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    texto = models.CharField(max_length = 500)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-data',]

    def __str__(self):
        return f'{self.autor.username}: "{self.texto}"'

receitas/forms.py
from django.forms import ModelForm
from .models import Post, Category
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['nome', 'tempo_de_preparo', 'foto_url', 'ingredientes', 'categorias']
        labels = ['Nome da Receita', 'Tempo de Preparo', 'Link para a foto', 'Ingredientes', 'Categorias']

receitas/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect 
from django.urls import reverse
from .models import Category, Comment, Post
from .forms import PostForm
from django.views import generic
from django.contrib.auth.models import User

class ListaDeReceitas(generic.ListView):
    model = Post
    template_name = 'receitas/list.html'
    context_object_name = 'lista_de_receitas'

class ListaDeCategorias(generic.ListView):
    model = Category
    template_name = 'receitas/list_cat.html'
    context_object_name = 'lista_de_categorias'

def listar_receitas(request, pk):
    list=[]
    a = Category.objects.get(id=pk)
    for post in Post.objects.all():
        if a in post.categorias.all():
            list.append(post)
    context = {"lista_2": list}
    return render(request, 'receitas/list_receitas.html', context)

class Contato(generic.TemplateView):
    template_name = 'receitas/contact.html'

def buscar_receitas(request):
    context = {}
    if request.GET.get('query', False):
        context = {"lista_de_receitas": Post.objects.filter(nome__icontains=request.GET['query'].lower())}
    return render(request, 'receitas/search.html', context)

class DetalheDaReceita(generic.DetailView):
    model = Post
    template_name = 'receitas/detail.html'

class Sobre(generic.TemplateView):
    template_name = 'receitas/about.html'

def criar_receita(request):
    if request.method == 'POST':
        post_nome = request.POST['nome']
        post_tempo_de_preparo = request.POST['tempo_de_preparo']
        post_foto_url = request.POST['foto_url']
        post_ingredientes = request.POST['ingredientes']
        post_categorias = request.POST['categorias']
        post = Post(nome=post_nome, tempo_de_preparo=post_tempo_de_preparo, foto_url=post_foto_url, ingredientes=post_ingredientes, categorias=Category.objects.get(id=post_categorias))
        post.save()
        return HttpResponseRedirect(reverse('detail', args=(post.id, )))
    else:
        form = PostForm()
        context = {'form': form}
        return render(request, 'receitas/create.html', context)

class AtualizarReceita(generic.UpdateView):
    model = Post
    fields = ['nome', 'tempo_de_preparo', 'foto_url', 'ingredientes']
    template_name = 'receitas/update.html'
    def get_success_url(self):
        return reverse('detail', kwargs={'pk': self.object.pk})

class DeletarReceita(generic.DeleteView):
    model = Post
    template_name = 'receitas/delete.html'
    def get_success_url(self):
        return reverse('list')

def criar_comentario(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        comentario_autor = User.objects.get_or_create(username=request.POST['autor'])[0]
        comentario_texto = request.POST['texto']
        comentario = Comment(autor=comentario_autor, texto=comentario_texto, post=post)
        comentario.save()
        return HttpResponseRedirect(
            reverse('detail', args=(post_id, )))
    else:
        context = { 'post': post }
        return render(request, 'receitas/comment.html', context)

receitas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Great+Vibes&family=Italianno&family=PT+Serif&family=Tangerine:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header>
        <div class="head">
            <img src="{% static 'logo.png' %}" alt="Logo">
            <h1>Suria Breads</h1>
        </div>
        <div class="nave">
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'list' %}"><i class="fas fa-home"></i> Página Inicial</a>
                    </li>
                    <li>
                        <a href="{% url 'about' %}"><i class="fas fa-info"></i> Sobre Nós</a>
                    </li>
                    <li>
                        <a href="{% url 'contact' %}"><i class="fas fa-phone-alt"></i> Contato</a>
                    </li>
                    <li>
                        <a href="{% url 'categorias' %}"><i class="fas fa-list-ul"></i> Categorias</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <main id="conteiner-principal">
        {% block content %}{% endblock %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>
</html>

receitas/templates/receitas/about.html
{% extends 'base.html' %}

{% block title %}
Sobre Nós
{% endblock title %}

{% block content %}
<section id="Home">
    <h2>Sobre Nós</h2>
    <p>
        Suria Breads é uma chef de cozinha amadora que ama se aventurar no
        mundo da panificação. Fazendo pães artesanais, croissants, esfihas,
        risotos, tortas, e muito mais, ela encantou suas amigas, vizinhos e
        agora possui fãs em todo o Brasil. Neste site, além do Instagram,
        ensinamos receitas diversas de forma simplificada, didática e visual, com
        dicas exclusivas que você só encontra no Suria Breads!
    </p>
    <p>
        Algumas de nossas receitas vêm de várias gerações, enquanto
        outras são mais recentes e ousadas. Mas de qualquer forma, 
        todas elas são simples e deliciosas.
    </p>
    <p>
        Obrigado por acessar nosso site e pelo seu apoio!
    </p>
</section>
{% endblock content %}

receitas/templates/receitas/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Fazer um Comentário</h2>
<form method="POST" action="{% url 'comment' post.id %}">
    {% csrf_token %}
    <p>
        <label for="id_autor">Nome: </label>
        <input type="text" name="autor" id="id_autor" />
    </p>
    <p>
        <label for="id_texto">Comentário: </label>
        <input type="text" name="texto" id="id_texto" />
    </p>
    <button type="submit">Comentar</button>
</form>

{% endblock content %}

receitas/templates/receitas/contact.html
{% extends 'base.html' %}

{% block title %}
Contato
{% endblock title %}

{% block content %}
<h2>Contato</h2>
<p>Para nos contatar, encontre-nos no</p>
<a href="https://www.instagram.com/suria_breads/">Instagram</a>
{% endblock content %}

receitas/templates/receitas/create.html
{% extends 'base.html' %}

{% block content %}

<h2>Criar Nova Receita</h2>
<form method="POST" action="{% url 'create' %}">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Criar</button>
</form>

{% endblock content %}

receitas/templates/receitas/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a receita "{{ post.nome }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

receitas/templates/receitas/detail.html
{% extends 'base.html' %}

{% block title %}

{{ post.nome }}

{% endblock title %}

{% block content %}

<div class="ingredientes">
    <h2>{{ post.nome }} ({{ post.tempo_de_preparo }} minutos)</h2>
    <h4>Postado em: {{ post.data|date:"d/m/Y" }} {{ post.data|time:"H:i" }} </h4>
    <img src="{{ post.foto_url }}" alt="Foto da Receita {{ post.nome }}" width="500px">
    <ul>
        <li><h3>Ingredientes:</h3>{{ post.ingredientes }}</li>
    </ul>
</div>

<section class="editar">
    <ul>
        <li><a href="{% url 'update' post.id %}">Editar</a></li>
        <li><a href="{% url 'delete' post.id %}">Apagar</a></li>
    </ul>
</section> 
<section class="ingredientes">
    <h3>Categorias</h3>
    <ul>
        {% for categoria in post.categorias.all %}
            <li><h4><a href="{% url 'receitas' categoria.id %}">{{ categoria.nome }}</a></h4></li>
        {% endfor %}
    </ul>
</section>
<div class="ingredientes">
    <h3>Comentários</h3>
    <ul>
        {% if post.comment_set.all %}
        {% for comment in post.comment_set.all %}
            <div class="comentario">
                <h4>{{ comment.autor }}: "{{ comment.texto }}"</h4>
            </div>
        {% endfor %}
        {% else %}
            <h4>Ainda não existem comentários nessa receita</h4>
        {% endif %}
    </ul>
    <a href="{% url 'comment' post.id %}"><i class="fas fa-pen"></i> Fazer um Comentário</a>
</div>

{% endblock content %}

receitas/templates/receitas/index.html
{% extends 'base.html' %}

{% block title %}
Suria Breads
{% endblock title %}

{% block content %}
<h1><i>Suria Breads</i></h1>
<p>Receitas deliciosas!!</p>
{% endblock content %}

receitas/templates/receitas/list.html
{% extends 'base.html' %}

{% block title %}

Suria Breads

{% endblock title %}

{% block content %}

<section class="nave">
    <nav>
        <ul>
            <li>
                <a href="{% url 'search' %}"><i class="fas fa-search"></i> Buscar Receitas</a>
            </li>
            <li>
                <a href="{% url 'create' %}"><i class="fas fa-pen"></i> Criar Receita</a>
            </li>
        </ul>
    </nav>
</section>

<section class="lista-de-cards">
    {% for post in lista_de_receitas %}
    <article class="card">
        <a href="{% url 'detail' post.id %}">
            <img src="{{ post.foto_url }}" alt="Foto da Receita {{ post.nome }}">
            <p>{{ post.nome }} ({{ post.tempo_de_preparo }} minutos)</p>
        </a>
    </article>
    {% endfor %}
</section>

{% endblock content %}

receitas/templates/receitas/list_cat.html
{% extends 'base.html' %}

{% block title %}

Categorias

{% endblock title %}

{% block content %}

<section class="lista-de-cards">
    {% for categoria in lista_de_categorias %}
    <article class="card">
        <a href="{% url 'receitas' categoria.id %}">
            <p>{{ categoria.nome }}</p>
        </a>
    </article>
    {% endfor %}
</section>


{% endblock content %}

receitas/templates/receitas/list_receitas.html
{% extends 'base.html' %}

{% block title %}
{{ categoria.nome }}
{% endblock title %}

{% block content %}

<section class="lista-de-cards">
    {% for post in lista_2 %}
    <article class="card">
        <a href="{% url 'detail' post.id %}">
            <img src="{{ post.foto_url }}" alt="Foto da Receita {{ post.nome }}">
            <p>{{ post.nome }} ({{ post.tempo_de_preparo }} minutos)</p>
        </a>
    </article>
    {% endfor %}
</section>


{% endblock content %}

receitas/templates/receitas/search.html
{% extends 'base.html' %}

{% block title %}
Buscar
{% endblock title %}

{% block content %}
<section id="Home">
    <h2>Busca de Receitas</h2>
    <form action="{% url 'search' %}">
        <p>
            <label for="id_query">Título:</label>
            <input type="text" name="query" id="id_query">
        </p>
        <button type="submit">Buscar</button>
    </form>
</section>

<section class="lista-de-cards">
    {% for post in lista_de_receitas %}
    <article class="card">
        <a href="{% url 'detail' post.id %}">
            <img src="{{ post.foto_url }}" alt="Foto da Receita {{ post.nome }}">
            <p>{{ post.nome }} ({{ post.tempo_de_preparo }} minutos)</p>
        </a>
    </article>
    {% endfor %}
</section>
{% endblock content %}

receitas/templates/receitas/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar a Receita {{ post.nome }}</h2>
<form method="POST" action="{% url 'update' post.id %}">
    {% csrf_token %}
    <p>
        <label for="id_nome">Título:</label>
        <input type="text" name="nome" id="id_nome" value="{{ post.nome }}" />
    </p>
    <p>
        <label for=" id_tempo_de_preparo">Tempo de Preparo:</label>
        <input type="number" name="tempo_de_preparo" id="id_tempo_de_preparo" value="{{ post.tempo_de_preparo }}" />
    </p>
    <p>
        <label for=" id_foto_url">URL da Foto:</label>
        <input type="url" name="foto_url" id="id_foto_url" value="{{post.foto_url}}" />
    </p>
    <p>
        <label for=" id_ingredientes">Ingredientes:</label>
        <input type="text" name="ingredientes" id="id_ingredientes" value="{{post.ingredientes}}" />
    </p>
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}